import type { GeneratedFile, GenerationModel } from '../model.ts';
import { makeGeneratedFile } from '../file-plan.ts';

export function emitReadme(model: GenerationModel): GeneratedFile[] {
  const content = `# ${model.project.name}\n\nGenerated by Risheh Website Template Factory C2 from \`risheh.build-spec.v1\`.\n\n## Stack\n- Next.js 16.3.x App Router\n- React 19.3.x\n- TypeScript strict mode\n- Tailwind CSS 4.x\n\n## Commands\n\n\`\`\`bash\nnpm install\nnpm run dev\nnpm run lint\nnpm run build\n\`\`\`\n\n## Generation identity\n- Industry: \`${model.industry.id}\`\n- Archetype: \`${model.industry.archetype}\`\n- Design DNA: ${model.design.dnaIds.map((id) => `\`${id}\``).join(', ')}\n- Direction: \`${model.locale.direction}\`\n\nFactual business content was not invented by the generator. Missing factual data is intentionally omitted or represented by neutral structural copy.\n`;
  return [makeGeneratedFile({ path: 'README.md', kind: 'doc', owner: 'readme', sources: ['project','industry','design','locale'], content, overwrite: 'replace-generated' })];
}
